# Generated by Django 4.2.4 on 2023-08-03 16:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jornada',
        ),
        migrations.AddField(
            model_name='user',
            name='jor1',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jor2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 40, 42, 940552, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
