# Generated by Django 4.2.4 on 2023-08-03 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_user_jornada_user_jor1_user_jor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jor3',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 42, 29, 803161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jor4',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 42, 39, 179004, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
