# Generated by Django 4.2.4 on 2023-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user_jor3_user_jor4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jor1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='jor2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='jor3',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='jor4',
            field=models.TimeField(),
        ),
    ]
