# Generated by Django 4.2.4 on 2023-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_user_jor1_alter_user_jor2_alter_user_jor3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=12)),
                ('ipaddress', models.CharField(max_length=24)),
                ('startup', models.DateTimeField()),
                ('visto', models.DateTimeField()),
            ],
        ),
    ]
