# Generated by Django 4.2.4 on 2023-08-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Dado',
        ),
        migrations.RenameField(
            model_name='dado',
            old_name='ipaddress',
            new_name='ipadd',
        ),
    ]
