# Generated by Django 4.2.4 on 2023-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_rename_data_dado_rename_ipaddress_dado_ipadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='ipadd',
        ),
        migrations.RemoveField(
            model_name='dado',
            name='startup',
        ),
        migrations.AlterField(
            model_name='dado',
            name='visto',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
