# Generated by Django 4.2.4 on 2023-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_dado_ipadd_remove_dado_startup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='hostname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dado',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
