# Generated by Django 4.2.4 on 2023-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_dado_hostname_alter_dado_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=64)),
                ('acao', models.CharField(max_length=64)),
            ],
        ),
    ]
