# Generated by Django 4.2.4 on 2023-08-14 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_sinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
